[package]
name = "potofu_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.11"
tokio = {version = '1', features = ["full"]}
dotenv = "0.15"
reqwest = {version = "*", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"